### ISSUE TITLE
ACPI names are *always* 4 characters

### ISSUE THREAD

**Issue by rudi48** [corpnewt/Hackintosh-Guide#10]
Hello CorpNewt,

Thank you very much for your excellent guide.

At one point, I think it needs a change:
    `'XHC' is represented as 'XHC_'`
see: [RehabMan](https://www.tonymacx86.com/threads/rename-xhci-to-xhc-usb-3-0-madness.195421/post-1271386)
Quote: ACPI names are *always* 4 characters. 'XHC' is represented as 'XHC_'. Read the ACPI spec.

Regards, Rudolf  DL5FA

**Comment by corpnewt** [comment]
Correct - often when represented as ASCII, the underscore is dropped.  If you convert `WEhDXw==` to ASCII, it becomes `XHC_`.  The guide is still accurate.

-CorpNewt

Edit for clarification:  The only time it is not labeled explicitly is in the comment, which Rehabman also "mislabels" in his [USBInjectAll config_patches.plist](https://github.com/RehabMan/OS-X-USB-Inject-All/blob/master/config_patches.plist):
```xml
				<dict>
					<key>Comment</key>
					<string>change XHC1 to XHC</string>
					<key>Find</key>
					<data>WEhDMQ==</data>
					<key>Replace</key>
					<data>WEhDXw==</data>
				</dict>
```
