### ISSUE TITLE
Why no Broadwell config.plist

### ISSUE THREAD

**Issue by helvenk** [corpnewt/Hackintosh-Guide#11]
I am working at i5 5200u , could you please provide a config.plist for Broadwell

**Comment by corpnewt** [comment]
From the [Prerequisites](https://github.com/corpnewt/Hackintosh-Guide/blob/master/README.md#prerequisites) section in the first page of the guide:

>This guide focuses on Desktops _ONLY_. There are other guides out there for laptops \(see [RehabMan's guide](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/) at TMac\) - but they're often _much more specific_ than this guide will be.

And i5-5200u is a mobile CPU (there are [_very few_](https://en.wikipedia.org/wiki/Broadwell_(microarchitecture)#Desktop_processors) Desktop Broadwell CPUs).

I would suggest reading through RehabMan's laptop guide linked above and in my guide - as it will likely be a much more applicable solution for your hardware.

-CorpNewt

**Comment by helvenk** [comment]
I have noticed the Desktop ONLY, but I'm just wondering why there's no Broadwell config. Now I know that's because there are few Broadwell Macs. Thanks for your reply.

**Comment by corpnewt** [comment]
Not a problem, best of luck.

-CorpNewt
