### ISSUE TITLE
ACPI trouble 

### ISSUE THREAD

**Issue by insanitus** [corpnewt/Hackintosh-Guide#12]
Hi folk;

 I been hit whit this type of error ACPI Exception ARE_NOT_Found 

 I tested the config.plist of Coffe Lake, Kaby Lake, Skylake, and 
I get  the error of ACPI Exception ARE_NOT_Found, also I try whit acpi=off but I not have success.

 I been looking around in the interwebs whit out any 
possible solution for my trouble.

 Can be possible that you can help me whit this?

Thanks in advance.

**Comment by corpnewt** [comment]
Not an issue with the guide - closing this issue as it's unrelated.  Your best bet is to ask in one of the Hackintosh forums (TMac, InsanelyMac, or /r/Hackintosh) or on one of the discord support forums.  This repo is for hosting the files for my guide - not troubleshooting.

-CorpNewt

**Comment by insanitus** [comment]
Ohh well, thanks for the explanation, I will try to ask in some of these forums  =̣^)
