### ISSUE TITLE
USB Installer - need to give a link/explanation w.r.t. "partial" Install downloads

### ISSUE THREAD

**Issue by hevisko** [corpnewt/Hackintosh-Guide#13]
Good day,

 There should be an explanation how to get the *full* Install image as the AppStore now only downloads a partial "stub" installer, so readers should be made aware that the case of this happening, that they should start the installer, let it download the full ~6GB installer image/data, abort/quit the installation when it request the reboot, and have that copied into the `Install macOS Mojave` directory before the installmedia scripts would work.

Should that be done inline, or rather as a separate page linked to from the "Create Install USB" page?

**Comment by corpnewt** [comment]
Not as common an issue as before - and not within the scope of the current guide.  At some point, I may add a troubleshooting section, but I haven't had time nor the drive to of late.

-CorpNewt
