### ISSUE TITLE
AptioMemoryFix no longer available in Clover ^v4988

### ISSUE THREAD

**Issue by hennessyevan** [corpnewt/Hackintosh-Guide#14]
Hey @corpnewt thanks for this guide, it's really easy to follow and I have never felt so confident about my hackintosh in the 5 years I've been using when as when I followed this guide.

`AptioMemoryFix.efi` no longer ships with new versions of Clover. According to [this ticket](https://sourceforge.net/p/cloverefiboot/tickets/591/#978f) `OsXAptioFix3Drv` is now the preferred driver. Recently I have been using this driver and haven't noticed any problems with stability, NVRAM. Should we change the docs at https://github.com/corpnewt/Hackintosh-Guide/blob/master/clover-setup.md#installing-clover to reflect these changes?

**Comment by fttx** [comment]
I agree, in addition, the new default driver folder has changed from `/drivers64UEFI` to `/drivers/UEFI`, and this path is already used by the installer

**Comment by corpnewt** [comment]
> `AptioMemoryFix.efi` no longer ships with new versions of Clover. According to this ticket

There appears to be some dust kicked up between Acidanthera and Slice with regards to crossover drivers.  It is still included by default with [Dids' Clover builds](https://cloverdb.com/) - and as his is the repo I suggest in the guide - I'll likely still include the `AptioMemoryFix` suggestion.

The screenshots of the Clover Customization options are antiquated, and need to be updated.  I use my own builds of Clover (built with my [CloverExtractor](https://github.com/corpnewt/CloverExtractor) script) - which include `AptioMemoryFix` and Acidanthera's `ApfsDriverLoader` for the screenshots - so even when using Dids' builds, there may be differences.

I think what makes the most sense is to update the screenshots, preserve my suggestions for `AptioMemoryFix`, but suggest `OsxAptioFix3Drv` as an alternative if using the official Clover package from SourceForge.

>in addition, the new default driver folder has changed from `/drivers64UEFI` to `/drivers/UEFI`, and this path is already used by the installer

I can add a note about this as well.  Currently, even the newest copies of Clover respect the prior layout of having efi drivers at `drivers64UEFI` - but will prioritize `drivers/UEFI` if found per the code starting at [this line](https://sourceforge.net/p/cloverefiboot/code/HEAD/tree/rEFIt_UEFI/refit/main.c#l1508).  I'll make a note that builds through r4982 use `drivers64UEFI`, r4983 through r4985 use `UEFIDrivers` (per [this commit](https://sourceforge.net/p/cloverefiboot/code/4983/tree//rEFIt_UEFI/refit/main.c?diff=504c3833fd48f873331ebd05:4982)), and r4986 and newer use `driver/UEFI`.

If I have an opportunity today, I'll update the guide.  Thanks for the suggestions.

-CorpNewt

**Comment by corpnewt** [comment]
Updated with [this commit](https://github.com/corpnewt/Hackintosh-Guide/commit/c5cf090ccce9b835b04d977d0f17a0427fe5b074).

-Corpnewt
