### ISSUE TITLE
USBMap Guide

### ISSUE THREAD

**Issue by hennessyevan** [corpnewt/Hackintosh-Guide#15]
I use your brilliant `USBMap` cli tool as do many others, I know there are other methods but given that it and this guide are both yours I think it could be good to have a section here on how to use it.

After using `USBMap` recently to get Catalina Beta to install I have to say it wasn't as complicated as the guides I came across made it out to be, especially with your tool although it can be hard to know where to start.

I was going to write a step by step guide for myself on it for future reference but if you think it would make sense in this guide I could put it here instead. lmk

**Comment by corpnewt** [comment]
If you already have a step-by-step guide put together, that would be very helpful.  I've been spread among a bunch of projects lately, and haven't gotten around to finishing my [mostly incomplete explanation](https://usb-map.gitbook.io/project/) of the issues and solutions.  I intended it to be a separate guide entirely though, as understanding the issues, reasons, and solutions can be quite a process.

-CorpNewt
