### ISSUE TITLE
Ivy Bridge config.plist

### ISSUE THREAD

**Issue by Plunger55** [corpnewt/Hackintosh-Guide#2]
I have a GA-Z68M-D2H motherboard with a i7-3770 CPU. Do you have the matching Ivy Bridge config.plist?

**Comment by corpnewt** [comment]
Not currently - I haven't had time to put together the ivy process yet as there are some special considerations to make.  I plan to work through some of that in the near future though.

**Comment by Plunger55** [comment]
Thanks for responding.

Looking forward to the update.

**Comment by TemKu** [comment]
I have been struggling to learn about and install a working version of Mojave.
Dell Optiplex 9010 SFF. (It has Windows 10 Pro installed and works.)
CPU: i7 3770
Chipset: Q77
GPU: Intel HD 4000
RAM: 8GB

I was able to get the Mojave installer on the USB Disk to mount and had a first attempt to install to a crucial SSD in the Dell. It did one restart and then seemed to freeze. I looked at the SSD on my Mac and saw that many installer pieces had copied over but the full installation never completed.

Any advice would be very much appreciated.

**Comment by 13parsecs** [comment]
> I have been struggling to learn about and install a working version of Mojave.
> Dell Optiplex 9010 SFF. (It has Windows 10 Pro installed and works.)
> CPU: i7 3770
> Chipset: Q77
> GPU: Intel HD 4000
> RAM: 8GB
> 
> I was able to get the Mojave installer on the USB Disk to mount and had a first attempt to install to a crucial SSD in the Dell. It did one restart and then seemed to freeze. I looked at the SSD on my Mac and saw that many installer pieces had copied over but the full installation never completed.
> 
> Any advice would be very much appreciated.

Make sure you ONLY have the 1 SSD in there for the Mac 'side'. Pull the Windows drive OUT of the chassis completely.

Even on _**real**_ macs (I have 7..!!) Mojave gets 'confused' if there is more than one drive/partition, or even a USB installer - a proper "create install media" one - present.

**Comment by TemKu** [comment]
As I do research to find out what works, or is intended to work with, the different processors and chipsets I realize that there might be a way to remove the guess work. I don't know. This idea occurred to me this evening. Can someone organize a list that shows what each processor group needs to function on a basic level. I am not sure if that is clear. 
I am referring to the vanilla settings needed to boot each processor + chipset group. I feel that this could help reduce the number of repetitive sounding messages on the forums or just at least provide a reference point. If it was a visual representation that would also help some of us to better understand where to start;-)
 I have managed to get one Hackintosh running, except for the ethernet port (which might need an intel driver). 
Also, had anyone suggested creating a repository database for each of the CPU+chipset groups?
I think that the information for each submittal doesn't need to be tested, but should include a description of the hardware and a Config.plist.
I am asking this just to make the whole process a little more efficient. I could be wrong, or could be asking for something very large and expensive to implement and support. I really don't know what it would take to do this. Also, I am thinking that it would be very helpful, but don't have any way to gather or present data showing there is a need. Anyway, good night!

**Comment by corpnewt** [comment]
@TemKu 
Ultimately that's the goal with the guide this repo is attached to.  To be fair though, it's a hefty chunk of work to maintain, and keeping up with the pace of the community (and Apple's releases) can be a bit much.  I haven't been able to sit down and work on the Ivy changes - but they're typically pretty close to the Haswell setup with a few changes:

1. Don't use _PluginType_
2. Drop the _CpuPm_ and _Cpu0Ist_ SSDT tables
3. If you have an HD 4000, use `0x0166000A` for the _AAPL,ig-platform-id_ if you connect your display to the mobo's outputs - or `0x01620006`/`0x01620007` for iMac13,1/iMac13,2 respectively if you only use the iGPU for compute tasks (none of these are required if you don't have a compatible iGPU)
4. If you mix an Ivy CPU with a 6-series board, you'll need to fake the IMEI as well (as real macs don't mix them):
 * - _config.plist -> ACPI -> Fixes_ needs both _AddDTGP_ and _AddIMEI_ enabled
 * - _config.plist -> Devices -> FakeID -> IMEI_ should be set to `0x1e3a8086`
5. Enable _config.plist -> KernelAndKextPatches -> AppleIntelCPUPM_ to avoid kernel panics when AICPUPM tries to write to a locked MSR 0xe2 register.
6. As a post-install step, you'll want to use Pike R. Alpha's [ssdtPRGen.sh](https://github.com/Piker-Alpha/ssdtPRGen.sh) script to generate an SSDT.aml for your CPU power management which gets placed in the EFI at _EFI -> CLOVER -> ACPI -> patched_

As an aside, I have experienced what @13parsecs mentioned as well - Mojave's installer seems to be quite easy to confuse if multiple drives are present (it always picks one of my random data drives to search for the _macOS Install Data_ folder) - so limiting the variables there could help.

-CorpNewt
