### ISSUE TITLE
Coffee lake: animations lag and iGPU Metal support 

### ISSUE THREAD

**Issue by fttx** [corpnewt/Hackintosh-Guide#4]
Hi,

I've followed your guide to build an hackintosh but i'm experiencing some animations lag in the Mission Control due to the lack of the iGPU metal support.

What i've tried so far:
- Using different SMBIOSes: 17.1, 18.1, 18.2, and 18.3
- Using different ig-platform-id: 0x3E9B0007 and 0x3E920003 (for each SMBIOS above)
- Using a different DisplayPort
- Recompiled and installed WhateverGreen and Lilu with the latest GitHub changes
- Removing all USB devices
- Update the BIOS to the latest version
- Flip the GPU BIOS switch
- Remove the shikigva=40 bootflag
- Remove the shikigva=40 bootflag and the Devices>Properties section

![image](https://user-images.githubusercontent.com/5663423/50375054-d2033f80-05f7-11e9-9d87-23a3c162e993.png)

Could the problem be related to some BIOS setting?  Like CSM UEFI/Legacy option?

My system: **CPU**: 8700k **Motherboard**: ROG STRIX Z370-I GAMING **GPU**: SAPPHIRE NITRO+ RADEON RX 580 8GB
Reddit post: https://www.reddit.com/r/hackintosh/comments/a6n4w4/8700k_rx_580_ui_lag/

**Comment by corpnewt** [comment]
In reading through that reddit post, there are a number of users who also claim to have stutters from time to time - and they all share the same Sapphire Nitro+ RX 580 you're using.  I wonder if the GPU is to blame?  You could try removing the RX 580 entirely, and setup the UHD 630 to drive the display and see if animations are choppy using only the iGPU as a test.

-CorpNewt

**Comment by fttx** [comment]
Ok, i've set the properties as follows:
![image](https://user-images.githubusercontent.com/5663423/50381991-fd883780-0694-11e9-8e6e-7e2595e11e03.png)
And switched to a 18,3 SMBIOS.

This is what System Report shows if i totally remove the RX 580:
![screenshot 2018-12-23 at 09 19 09](https://user-images.githubusercontent.com/5663423/50381995-214b7d80-0695-11e9-8fb3-30bf0c171bc8.png)

There are two issues: 
- The 4K resolution doesn't work
- The animations smoothness is not consistent, sometimes they are smooth as butter and sometimes not. Besides that, is the iGPU powerful enough to drive a 4k + a 1080 monitor without losing frames?

**EDIT I**:
After that i put back the RX 580, Metal support showed up in the system report, i guess that it was due to the fact that my default graphics display was set to PCI-E in the BIOS settings.

 ![image](https://user-images.githubusercontent.com/5663423/50382466-0d594900-06a0-11e9-9cbc-31950ad29bd2.png)

The lag still persists.

**EDIT II**:
I've tried to connect one display to the RX 580 and the other to the motherboard, and the lag presents at the same time in both monitors

**EDIT III**:
If i remove the Devices/Properties section from the config.plist the iGPU 4k works

**Comment by fttx** [comment]
This issue isn't present on High Sierra: if i try to boot with the exact same EFI folder to High Sierra everything works as expected.

On High Sierra the system report shows _Supported, feature set macOS GPUFamily**1 v3**_ instead of _Supported, feature set macOS GPUFamily**2 v1**_, and also the Device ID is `0x5912` instead of `0x3e92`

**Comment by kinoute** [comment]
I have also lags with an UHD 630 using the Launchpad for example. But it's only from time to time. 

I can almost reproduce it 100% of the time if I'm watching a 1080p60 video on Youtube and use Launchpad. If I navigate with the mouse wheel in it, I can see it's lagging. But I don't have a dGPU though, only using the UHD 630 of my i5-8400 on 10.14.3.

Here is my EFI repo if interested: https://github.com/kinoute/Hack-Z370-HD3P-i5-8400

**Comment by fttx** [comment]
What is the resolution of your monitor(s)?

**Comment by kinoute** [comment]
An old 24" 1080p monitor.

**Comment by fttx** [comment]
I can confirm that it's not caused from the dGPU, i've tried with another card (AMD R9 270X) and it still does lag.

**Comment by kinoute** [comment]
Did somebody try by setting its VRAM to 2048?



2019-03-10 14:20:37 +0000 filippo <notifications@github.com> :

**Comment by fttx** [comment]
I finally found an answer: it's a Mojave bug:

- https://www.insanelymac.com/forum/topic/335781-mojave-v-sync-makes-ui-feel-laggy/?page=2
- https://forums.developer.apple.com/thread/112468

**Comment by corpnewt** [comment]
Considering it's not an issue related to the guide, I'm going to close the issue. If that changes, I'll reopen it.

-CorpNewt
