### ISSUE TITLE
Looks like this line is incorrect?

### ISSUE THREAD

**Issue by lmuzzio** [corpnewt/Hackintosh-Guide#7]
https://github.com/corpnewt/Hackintosh-Guide/blob/5755943215d9c7d696c138b3013f0d954b29bc41/Configs/CoffeeLake/config.plist#L97

**Comment by corpnewt** [comment]
Are you saying that because it's ordered differently than in the guide?  The order doesn't matter.

-CorpNewt

**Comment by lmuzzio** [comment]
Yes, thanks for letting me know.

**Comment by corpnewt** [comment]
Not a problem.

-CorpNewt
